name: UI E2E Test

on:
  workflow_dispatch:
    inputs:
      ref:
        description: Git ref to test
        required: false
        default: main
      spec:
        description: Path to E2E spec file (selenium or wdio)
        required: false
        default: e2e/ui_smoke.test.mjs

permissions:
  contents: read

concurrency:
  group: ui-e2e-${{ github.ref }}
  cancel-in-progress: true

jobs:
  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      TAURI_DRIVER_URL: http://127.0.0.1:4444
      ARTIFACTS_DIR: artifacts

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref || github.ref }}

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      # --- Rust is required because you call `cargo install tauri-driver`
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libwebkit2gtk-4.1-dev \
            build-essential \
            wget \
            file \
            libxdo-dev \
            libssl-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev \
            xvfb \
            webkit2gtk-driver

      - name: Install JS deps
        run: pnpm install --frozen-lockfile

      - name: Create basic test runner
        run: |
          echo "Skipping package builds for basic infrastructure test"

      - name: Install tauri-driver
        run: cargo install tauri-driver

      - name: Setup test environment  
        run: |
          mkdir -p run
          mkdir -p "$ARTIFACTS_DIR"
          echo "Test environment ready"

      - name: Run spec
        run: |
          node "${{ inputs.spec || 'e2e/ui_smoke.test.mjs' }}" > run/test.log 2>&1 || exit_code=$?
          cp -f run/test.log "$ARTIFACTS_DIR"/test.log || true
          exit ${exit_code:-0}

      - name: Cleanup
        if: always()
        run: |
          echo "Test completed"

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ui-e2e-artifacts
          path: |
            ${{ env.ARTIFACTS_DIR }}/
            run/app.log
            run/driver.log
            run/test.log
